project:
  type: website

website:
  title: "Cursos"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Cursos"
        menu:
          - text: "Course 1"
            href: courses/mediciones.qmd
          - text: "Course 2"
            href: courses/procimagenes.qmd
