project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Cursos"
        menu:
          - text: "Mediciones Biomédicas"
            href: mediciones.qmd
          - text: "Procesamiento de Imágenes"
            href: proc-imagenes.qmd
