---
title: "BME423 - Procesamiento de imágenes médicas"
tbl-colwidths: [5,20,10,10,10,10]
---

Bienvenidos al sitio web del curso de *procesamiento de imágenes médicas*. En este sitio encontrarás la información relacionada con las clases y las actividades desarrolladas en el transcurso del semestre.

## Enlaces importantes

-   [Planificación y material visto en clases.](bme423-planificacion.html)
-   [Ejercicios.](bme423-ejercicios.html)
-   [Evaluaciones (nivel BME).](bme423-eval-bme.html)
-   [Evaluaciones (nivel MCIB y DCIS).](bme423-eval-mcib-dcis.html)
-   [Aula virtual de pregrado.](https://aulavirtualpregrado.uv.cl/)
-   [Aula virtual de postgrado.](https://aulavirtualpostgrado.uv.cl/)

## Clases y laboratorios

|         | Día       | Hora          | Lugar            |
|---------|-----------|---------------|------------------|
| Cátedra | Jueves    | 08:30 - 11:45 | 202 (Hucke)      |
| Lab     | Miércoles | 14:30 - 17:45 | Lab. 302 (Hucke) |

## Objetivos

Al finalizar el semestre, será capaz de:

-   **Comprender y aplicar los fundamentos teóricos y prácticos del procesamiento de imágenes médicas:** Abordar desde la adquisición y representación de imágenes hasta el uso de técnicas de mejora y preprocesamiento, incluyendo operaciones puntuales y sobre histogramas, filtrado espacial, transformada de Fourier, filtrado mediante ecuaciones diferenciales y análisis del impacto del ruido y degradación en imágenes médicas.

-   **Diseñar, implementar y evaluar algoritmos de segmentación y análisis cuantitativo:** Desarrollar métodos para aislar, identificar y medir estructuras anatómicas o patológicas en imágenes médicas, utilizando enfoques clásicos y avanzados que garanticen precisión y reproducibilidad.

-   **Desarrollar y evaluar algoritmos de reconocimiento de patrones y aprendizaje automático:** Aplicar métodos de inteligencia artificial, aprendizaje supervisado (ANN, CNN), y diseño de pipelines automatizados para la clasificación y detección en imágenes médicas.

-   **Analizar y ejecutar métodos de reconstrucción:**: Implementar algoritmos para la reconstrucción volumétrica y bidimensional a partir de proyecciones, comprendiendo su aplicación en modalidades como tomografía.

-   **Interpretar especificaciones técnicas y parámetros:** Analizar especificaciones críticas de equipos y softwares de procesamiento de imágenes médicas para seleccionar estrategias y herramientas apropiadas en aplicaciones clínicas.

-   **Integrar conocimientos en proyectos aplicados:** Planificar y ejecutar proyectos prácticos/laboratorios, documentando metódicamente los procedimientos, resultados y conclusiones, en concordancia con estándares académicos y éticos.

## Material visto en clases

\[14-08\] [Introducción](/bme423-slides/bme423_00_intro.pdf "slides"){aria-label="slides intro"} [Definiciones](/bme423-slides/bme423_01_def.pdf "slides"){aria-label="slides definiciones"}

\[21-08\] [Operaciones puntuales y en histogramas](/bme423-slides/bme423_02_oppuntuales.pdf "slides"){aria-label="slides operaciones puntuales"} [Ruido / degradación](/bme423-slides/bme423_03_degradacion.pdf "slides"){aria-label="slides degradación"} [Filtros espaciales](/bme423-slides/bme423_04_filtradoespacial.pdf "slides"){aria-label="slides filtrado espacial"} [Ejemplo convolución](/bme423-slides/bme423_04_convolución%20ejemplo.pdf "slides"){aria-label="slides convolución"}

## Laboratorios

[Lab 1](/bme423-labs/lab1.html), [📖 Chap3 - Rafael Gonzalez](/bme423-labs/RGCh03.pdf)

```{=html}
<!-- | Lab | 27-08 |  |  |  |  |  |
| Cátedra | 28-08 | [Filtros mediante PDE](/bme423-slides/bme423_05_diff.pdf) | [🖥️ - difusión lineal](/bme423-ejemplos/difusion_lineal.html) |  | [**Entrega de temas de proyecto**]{.my-green} | [**Entrega de temas de proyecto**]{.my-green} |
| Lab | 03-09 |  |  |  |  |  |
| [**Cátedra**]{.my-red} | [**04-09**]{.my-red} | [**Clase suspendida**]{.my-red} |  |  |  |  |
| Lab | 10-09 |  |  | [Lab 2](/bme423-labs/lab2.html) | Lab 2 | Lab 2 |
| Cátedra | 11-09 | [Fourier](/bme423-slides/bme423_08_fourier.pdf) |  |  |  |  |
| [**Lab**]{.my-red} | [**17-09**]{.my-red} | [**Fiestas patrias**]{.my-red} |  |  |  |  |
| [**Cátedra**]{.my-red} | [**18-09**]{.my-red} | [**Fiestas patrias**]{.my-red} |  |  |  |  |
| Lab | 24-09 |  |  |  |  |  |
| Cátedra | 25-09 |  |  |  |  |  |
| Lab | 01-10 |  |  | [Lab 3](/bme423-labs/lab3.html) | Lab 3 | Lab 3 |
| [**Cátedra**]{.my-green} | [**02-10**]{.my-green} | [**Prueba 1**]{.my-green} |  |  | [**Presentación avance**]{.my-green} | [**Presentación avance**]{.my-green} |
| Lab | 08-10 |  |  |  |  |  |
| Cátedra | 09-10 | Transformaciones geométricas | [🖥️](/bme423-slides/bme423_07_transf_geom.pdf "slides"){aria-label="slides transformaciones geométricas"} |  |  |  |
| [**Lab**]{.my-red} | [**15-10**]{.my-red} | [**Pausa**]{.my-red} |  |  |  |  |
| [**Cátedra**]{.my-red} | [**16-10**]{.my-red} | [**Pausa**]{.my-red} |  |  |  |  |
| Lab | 22-10 |  |  |  |  |  |
| Cátedra | 23-10 | Segmentación I | [🖥️](/bme423-slides/bme423_09_segmentación.pdf "slides"){aria-label="slides segmentación"} |  |  |  |
| Lab | 29-10 |  |  | [Lab 4](/bme423-labs/lab4.html) | Lab 4 | Lab 4 |
| Cátedra | 30-10 | Segmentación I |  |  |  |  |
| Lab | 05-11 |  |  |  |  |  |
| Cátedra | 06-11 | Morfología matemática | [🖥️](/bme423-slides/bme423_06_morfología%20imagen%20binaria.pdf "slides"){aria-label="slides morfología binaria"}<br>[🖥️](/bme423-slides/bme423_06_morfología%20binaria%20ejemplo.pdf "slides"){aria-label="slides morfología binaria"}<br>[🖥️](/bme423-slides/bme423_06_morfología%20ejemplo%20region%20growing.pdf "slides"){aria-label="slides morfología binaria"} |  |  |  |
| Lab | 12-11 |  |  |  |  |  |
| [**Cátedra**]{.my-green} | [**13-11**]{.my-green} | [**Prueba 2**]{.my-green} |  |  | [**Presentación avance**]{.my-green} | [**Presentación avance**]{.my-green} |
| Lab | 19-11 |  |  | Lab 5 | Lab 5 | Lab 5 |
| Cátedra | 20-11 | IA en procesamiento de imágenes | [slides FANN](/bme423-slides/bme423_10_rec-patrones_1-ANN.pdf "slides"){aria-label="slides IA patrones"}<br>[slides CNN-1](/bme423-slides/bme423_10_rec-patrones_2-CNN-1.pdf "slides"){aria-label="slides IA patrones"}<br>[slides CNN-2](/bme423-slides/bme423_10_rec-patrones_2-CNN-2.pdf "slides"){aria-label="slides IA patrones"}<br>[slides repr](/bme423-slides/bme423_10_rec-patrones_2-representacion.pdf "slides"){aria-label="slides IA patrones"}<br>[🖥️ - conv](/bme423-ejemplos/cnn-01-conv.html)<br>[🖥️ - modelos preentrenados](/bme423-ejemplos/cnn-02-pretr.html)<br>[🖥️ - arquitecturas](/bme423-ejemplos/cnn-03-design.html)<br>[🖥️ - fully convolutional](/bme423-ejemplos/cnn-04-fullycnn.html)<br>[🖥️ - object localization](/bme423-ejemplos/cnn-05-cnn-class-loc.html) |  |  |  |
| Lab | 26-11 |  |  |  |  |  |
| Cátedra | 27-11 | Segmentación II |  |  |  |  |
| Lab | 03-12 |  |  |  |  |  |
| Cátedra | 04-12 | Reconstrucción<br>Reconstrucción a partir de proyecciones | [🖥️](/bme423-slides/bme423_11_recontruccion.pdf "slides"){aria-label="slides reconstrucción"}<br>[🖥️](/bme423-slides/rec_from_proj.pdf "slides"){aria-label="reconstrucción desde proyecciones"} |  | [**Entrega proyecto**]{.my-green} | [**Entrega proyecto**]{.my-green} |
| Lab | 10-12 |  |  |  |  |  |
| [**Cátedra**]{.my-green} | [**11-12**]{.my-green} | [**Prueba 3**]{.my-green} |  |  | [**Prueba**]{.my-green} | [**Prueba**]{.my-green} |
| [**Lab**]{.my-green} | [**17-12**]{.my-green} | [**Pruebas extraordinarias**]{.my-green} |  |  |  |  |
| [**Cátedra**]{.my-green} | [**18-12**]{.my-green} | [**Pruebas extraordinarias**]{.my-green} |  |  |  |  |
::: -->
```

## Bibliografía y otros recursos

-   [Digital image processing](https://www.pearson.com/en-us/subject-catalog/p/digital-image-processing/P200000003224/9780137848560?srsltid=AfmBOopbevUva4BjsSzl5WR1Yqui5kgNYtqmZtrPtCEes0f43VrRM3je), Rafael González, Richard Woods. Ediciones 2, 3 o 4.
-   [Handbook of medical image processing and analysis]() I. Bankman.
-   [Pattern Recognition and Machine Learning](https://link.springer.com/book/9780387310732), Christopher Bishop (2006).
-   [Image Processing, Analysis, and Machine Vision]() M. Sonka, V. Hlavac, R. Boyle (2008, 2015).
-   [Scikit-image](https://scikit-image.org)
-   [OpenCV](https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html)
-   [SimpleITK](https://simpleitk.readthedocs.io/en/master/)
-   [VTK](https://examples.vtk.org/site/Python/)\
-   Nibabel, pydicom

## Equipo docente

#### **Profesor:** Dr. Alejandro Veloz - [alejandro.veloz\@uv.cl](mailto:alejandro.veloz@uv.cl)

-   **Horario de atención:** Lunes 09:00-10:00 (solicitud vía correo)

#### **Ayudante:**

-   **Horario de atención:**

## Políticas del Curso

### Integridad Académica

Se espera que los estudiantes actúen con honestidad e integridad. No mentir, hacer trampa ni plagiar en trabajos académicos o no académicos. Todo trabajo presentado debe ser propio, a menos que se permita expresamente la colaboración. Debe citar adecuadamente todas las fuentes utilizadas, incluyendo código tomado de recursos en línea. El material no citado o mal referenciado **puede considerarse plagio**.

### Uso de Herramientas de Inteligencia Artificial (IA)

El uso de herramientas y recursos de IA está permitido y se fomenta. Sin embargo, se debe explicitar cuándo y cómo se usan estas herramientas en las tareas y trabajos relacionados con el curso. Debe especificar qué contenidos y/o códigos son generados con IA. Se espera total transparencia para mantener la integridad académica: no revelar el uso de IA puede considerarse una violación de las políticas del curso.

### Colaboración

Salvo que expresamente se indique trabajo en grupo, todas las tareas deben realizarse de forma individual. Se permite la discusión general con compañeros, pero no compartir respuestas detalladas ni código. Para proyectos en equipo, debe colaborar únicamente dentro de su grupo.

### Uso de código y recursos online

Puede consultar y utilizar recursos en línea. Todo código o material tomado de fuentes externas debe ser citado correctamente.

### Entregas tardías {#entregas-tardias}

Dispone de un total de 4 días de retraso que puede utilizar a gusto a lo largo del semestre en cualquiera de las evaluaciones del curso. Los días de retraso le permiten entregar laboratorios, tareas **sin penalización**. Retrasos superiores a 12 horas, se consideran como un día completo de retraso. Considere hacer uso de este *beneficio* en situaciones significativas o imprevistas. Si tiene problemas a largo plazo que afecten tu desempeño, se recomienda informar al profesor o jefe de carrera.

### Recalificaciones

Las solicitudes de revisión deben hacerse dentro de la semana posterior a la devolución de la calificación. Solo se considerarán solicitudes fundamentadas en base a la rúbrica proporcionada. Toda la pregunta será revisada nuevamente, lo que puede implicar aumento o disminución de puntos.

```{=html}
<!-- 
### Asistencia

Los estudiantes son responsables de asistir a clase; se espera una asistencia regular. Los estudiantes que asistan a más del 70% de las clases serán eximidos de rendir una prueba final al término del semestre. 
-->
```